main = "index.ts"
name = "northwind-worker"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"
account_id = "4ada3fc2e7dcf09a09749af670622778"
# logpush = true

[[routes]]
pattern = "api.cf-dev-platform.com"
custom_domain = true

[observability]
enabled = true

[dev]
port = 8789

[placement]
mode = "smart"

[[d1_databases]]
binding = "DB"
database_name = "northwind"
database_id = "1247ada2-21d0-4a5a-920d-262951bbf53b"

[[kv_namespaces]]
binding = "PRODUCT_SEARCH_CACHE"
id = "2780b6dfff604d9eab087fcade63ceb0"

[[vectorize]]
binding = "VECTORIZE"
index_name = "northwind-vector-db"
